#!/usr/bin/env bash
set -euo pipefail

# AISecOps Labs — Interactive Setup Script
# Sets up the Docker-based lab environment for "Attacking, Defending, and Leveraging AI"

# POSIX-compatible lowercase (macOS ships Bash 3.2, no ${var,,})
to_lower() { echo "$1" | tr '[:upper:]' '[:lower:]'; }

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   AISecOps Labs — Environment Setup          ║${NC}"
echo -e "${BOLD}║   Attacking, Defending, and Leveraging AI     ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Check prerequisites ──────────────────────────────────────────────

echo -e "${BOLD}[1/6] Checking prerequisites...${NC}"

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo -e "${RED}ERROR: $1 is not installed. Please install it and try again.${NC}"
        exit 1
    fi
    echo -e "  ${GREEN}✓${NC} $1 found"
}

check_cmd docker
check_cmd git

# Check for docker compose (v2 plugin)
if docker compose version &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} docker compose found"
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    echo -e "  ${YELLOW}!${NC} Using legacy docker-compose"
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}ERROR: docker compose is not available. Please install Docker Compose v2.${NC}"
    exit 1
fi

echo ""

# ── Step 2: Initialize/update git submodules ─────────────────────────────────

echo -e "${BOLD}[2/6] Initializing git submodules...${NC}"
git submodule update --init --recursive
echo -e "  ${GREEN}✓${NC} AI-CTF submodule ready"
echo ""

# ── Step 3: Backend selection ────────────────────────────────────────────────

echo -e "${BOLD}[3/6] Configuring LLM backend...${NC}"
echo ""
echo "  The CTF challenges need an LLM backend. You can use:"
echo "    1) OpenAI API  — Faster, requires API key, costs money"
echo "    2) Ollama      — Free, local, requires ~8GB disk + RAM"
echo ""

read -rp "  Do you have an OpenAI API key? [y/N]: " has_openai

PROFILES=()

has_openai=$(to_lower "$has_openai")
if [[ "$has_openai" == "y" || "$has_openai" == "yes" ]]; then
    LLM_BACKEND="openai"
    CTF_MODEL="gpt-4.1-mini"
    CTF_VISION_MODEL="gpt-4.1-mini"

    read -rp "  Enter your OpenAI API key: " OPENAI_API_KEY
    if [[ -z "$OPENAI_API_KEY" ]]; then
        echo -e "${RED}ERROR: API key cannot be empty.${NC}"
        exit 1
    fi

    OPENAI_API_BASE_URL="https://api.openai.com/v1"
    echo -e "  ${GREEN}✓${NC} Using OpenAI backend (gpt-4.1-mini)"
else
    LLM_BACKEND="ollama"
    CTF_MODEL="llama3.1:8b"
    CTF_VISION_MODEL="llama3.2-vision:11b"
    OPENAI_API_KEY=""
    OPENAI_API_BASE_URL=""
    PROFILES+=("ollama")
    echo -e "  ${GREEN}✓${NC} Using Ollama backend (llama3.1:8b)"
    echo -e "  ${YELLOW}!${NC} First startup will download ~4.7GB + ~6.4GB for models"
fi

echo ""

# ── Step 4: GPU detection ───────────────────────────────────────────────────

echo -e "${BOLD}[4/6] Detecting GPU...${NC}"

GPU_COMPOSE=""
if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} NVIDIA GPU detected"
    read -rp "  Enable GPU acceleration? [Y/n]: " use_gpu
    use_gpu=$(to_lower "$use_gpu")
    if [[ "$use_gpu" != "n" && "$use_gpu" != "no" ]]; then
        GPU_COMPOSE="-f docker-compose.gpu.yml"
        echo -e "  ${GREEN}✓${NC} GPU acceleration enabled"
    fi
else
    echo -e "  ${YELLOW}!${NC} No NVIDIA GPU detected (using CPU)"
fi

echo ""

# ── Step 5: Generate .env ───────────────────────────────────────────────────

echo -e "${BOLD}[5/6] Generating .env file...${NC}"

cat > .env << ENVEOF
# Generated by setup.sh on $(date)
# ===== Model Configuration =====
LLM_BACKEND=${LLM_BACKEND}
OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
CTF_MODEL=${CTF_MODEL}
CTF_VISION_MODEL=${CTF_VISION_MODEL}

# ===== Port Configuration =====
OLLAMA_PORT=11435
OPENWEBUI_PORT=4242
PIPELINES_PORT=9099
CTF_JUPYTER_PORT=8888
NOTEBOOKS_PORT=8889

# ===== CTF Configuration =====
OPENWEBUI_URL=http://open-webui:8080
CTF_ADMIN_EMAIL=admin@ctf.local
CTF_ADMIN_PASSWORD=ctf_admin_password
CTF_ADMIN_NAME=CTF Admin
CTF_USER_EMAIL=ctf@ctf.local
CTF_USER_PASSWORD=Hellollmworld!
CTF_USER_NAME=ctf_user
JUPYTER_TOKEN=AntiSyphonBlackHillsTrainingFtw!
NOTEBOOKS_TOKEN=aisecops2026

# CTF Flags
CTF_FLAG_CHALLENGE_1=WhatKindOfArchaeologistCarriesAWeapon?
CTF_FLAG_CHALLENGE_2=DoYouHaveCosmicAllergyMeds?
CTF_FLAG_CHALLENGE_3=ItsJustWindWindHappens
CTF_FLAG_CHALLENGE_4=MaybourneYouAreAnIdiotEveryDayOfTheWeekWhyCouldntYouHaveJustTakenOneDayOff?
CTF_FLAG_CHALLENGE_5=WhatIsAnOprah?
CTF_FLAG_CHALLENGE_6=TheGateIsOpenAndTheStarsAreRight
CTF_FLAG_CHALLENGE_7=Baal?AsInBocce?
CTF_FLAG_CHALLENGE_8=OfCourseIDareMockYou
CTF_FLAG_CHALLENGE_9=DialTheSeventhChevron
CTF_FLAG_CHALLENGE_10=WereNotTheBadGuysThisTime
CTF_FLAG_CHALLENGE_11=TheOnlyThingWeHaveToFearIsFearItself

ENVEOF

echo -e "  ${GREEN}✓${NC} .env generated"
echo ""

# ── Step 6: Build and start ─────────────────────────────────────────────────

echo -e "${BOLD}[6/6] Building and starting services...${NC}"
echo ""

# Build the profile arguments
PROFILE_ARGS=""
for p in "${PROFILES[@]}"; do
    PROFILE_ARGS="$PROFILE_ARGS --profile $p"
done

echo -e "  Running: ${COMPOSE_CMD} -f docker-compose.yml ${GPU_COMPOSE} ${PROFILE_ARGS} up -d --build"
echo ""

${COMPOSE_CMD} -f docker-compose.yml ${GPU_COMPOSE} ${PROFILE_ARGS} up -d --build

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║   Setup Complete!                            ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Access URLs:${NC}"
echo -e "  CTF Challenges (Open WebUI):  ${GREEN}http://localhost:4242${NC}"
echo -e "  CTF Jupyter (challenges 7/8): ${GREEN}http://localhost:8888${NC}"
echo -e "  Lab Notebooks (Labs 1-10):    ${GREEN}http://localhost:8889${NC}"
echo -e "  Pipelines:                    ${GREEN}http://localhost:9099${NC}"
if [[ " ${PROFILES[*]} " =~ " ollama " ]]; then
    echo -e "  Ollama API:                   ${GREEN}http://localhost:11435${NC}"
fi
echo ""
echo -e "${BOLD}Credentials:${NC}"
echo -e "  CTF Login:     ${YELLOW}ctf@ctf.local${NC} / ${YELLOW}Hellollmworld!${NC}"
echo -e "  CTF Admin:     ${YELLOW}admin@ctf.local${NC} / ${YELLOW}ctf_admin_password${NC}"
echo -e "  CTF Jupyter:   Token: ${YELLOW}AntiSyphonBlackHillsTrainingFtw!${NC}"
echo -e "  Lab Notebooks: Token: ${YELLOW}aisecops2026${NC}"
echo ""
echo -e "${BOLD}Notes:${NC}"
echo -e "  - The ctf-setup container will initialize challenges (may take a minute)"
echo -e "  - Wait for ctf-setup to finish before using the CTF"
echo -e "  - Check status with: ${COMPOSE_CMD} ps"
echo -e "  - View logs with:   ${COMPOSE_CMD} logs -f ctf-setup"
echo ""
